### ISSUE TITLE
Breve?

### ISSUE THREAD

**Issue by RubenVerg** [kolmogorov42/maiuscole-accentate#1]
Suggerimento: aggiungi una deadkey per la breve (`̆`) che é comoda se scrivi latino o Esperanto :()

**Comment by kolmogorov42** [comment]
Non c'è?
<kbd>Shift</kbd> + <kbd>AltGr</kbd> + <kbd>ù</kbd>
ăĕĭŏŭ
Stand-alone: ˘ (la ottengo con la dead key seguita da <kbd>Spazio</kbd>)

**Comment by RubenVerg** [comment]
Ah scusa, non l'ho vista ops

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
